# Tutorial on how to use the shared package

In your virtual environment, you can run the following command to install the shared package:
```bash
pip install -e .
```

After that, you can import the package in your Python code and use it to run the model and plot the results, as shown in the code snippets below.

In [11]:
from shared.models import energyscope_original_snapshot_2023
from shared.utils import run_model
from shared.plotting import plot_sankey
from shared.plotting import plot_sankey_co2
from shared.utils import load_snapshot
from shared.utils import run_model

In [12]:
results = run_model(energyscope_original_snapshot_2023)

Gurobi 13.0.2:

In [14]:
plot_sankey(results)

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [15]:
plot_sankey_co2(results)

In [16]:
snapshot_2050 = load_snapshot(2050)

In [17]:
result_2050 = run_model(snapshot_2050)

Gurobi 13.0.2:

In [18]:
plot_sankey(result_2050)

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [19]:
plot_sankey_co2(result_2050)

In [ ]:
result_2050.parameters['']

{'avail':                                 avail  Run
 index
 ACETIC_ACID                       inf    0
 ACETONE                           inf    0
 BENZENE                           inf    0
 BIOMASS_AGRICULTURE_DEJECTION  4149.0    0
 BIOMASS_AGRICULTURE_RESIDUAL   2293.0    0
 ...                               ...  ...
 WASTE_BIO                         0.0    0
 WASTE_FOS                         0.0    0
 WET_BIOMASS                       0.0    0
 WOOD                              0.0    0
 XYLENE                            inf    0

 [84 rows x 2 columns],
 'bio_ratio':    bio_ratio  Run
 0          0    0,
 'c_inv':                              c_inv  Run
 index
 AFC                     629.639000    0
 ALKALINE_ELECTROLYSIS  1274.606192    0
 AL_MAKING                 0.000000    0
 AL_MAKING_HR              0.000000    0
 AN_DIG                 1807.811000    0
 ...                            ...  ...
 TRUCK_SH_PROPANE_SD       0.000000    0
 UNMINEABLE_COAL_SEAM      0.008000    0
 WIND_OFFSHORE          3551.555199    0
 WIND_ONSHORE           1791.957171    0
 WOOD_METHANOL          2414.476867    0

 [690 rows x 2 columns],
 'c_maint':                           c_maint  Run
 index
 AFC                     12.590000    0
 ALKALINE_ELECTROLYSIS   24.651516    0
 AL_MAKING                0.000000    0
 AL_MAKING_HR             0.000000    0
 AN_DIG                 161.226000    0
 ...                           ...  ...
 TRUCK_SH_PROPANE_SD      0.000000    0
 UNMINEABLE_COAL_SEAM     0.000000    0
 WIND_OFFSHORE          135.493080    0
 WIND_ONSHORE            60.420601    0
 WOOD_METHANOL          120.723867    0

 [690 rows x 2 columns],
 'c_op':                       c_op  Run
 index0      index1
 ACETIC_ACID 1       0.0723    0
             2       0.0723    0
             3       0.0723    0
             4       0.0723    0
             5       0.0723    0
 ...                    ...  ...
 XYLENE      8       0.0812    0
             9       0.0812    0
             10      0.0812    0
             11      0.0812    0
             12      0.0812    0

 [1008 rows x 2 columns],
 'c_p':                         c_p  Run
 index
 AFC                    0.97    0
 ALKALINE_ELECTROLYSIS  0.90    0
 AL_MAKING              0.85    0
 AL_MAKING_HR           0.85    0
 AN_DIG                 1.00    0
 ...                     ...  ...
 TRUCK_SH_PROPANE_SD    1.00    0
 UNMINEABLE_COAL_SEAM   0.85    0
 WIND_OFFSHORE          1.00    0
 WIND_ONSHORE           1.00    0
 WOOD_METHANOL          0.86    0

 [690 rows x 2 columns],
 'c_p_t':                       c_p_t  Run
 index0        index1
 AFC           1         1.0    0
               2         1.0    0
               3         1.0    0
               4         1.0    0
               5         1.0    0
 ...                     ...  ...
 WOOD_METHANOL 8         1.0    0
               9         1.0    0
               10        1.0    0
               11        1.0    0
               12        1.0    0

 [8208 rows x 2 columns],
 'c_tax': Empty DataFrame
 Columns: [c_tax, Run]
 Index: [],
 'c_tax_co2':    c_tax_co2  Run
 0          0    0,
 'c_tax_fuel':    c_tax_fuel  Run
 0           0    0,
 'c_tax_import': Empty DataFrame
 Columns: [c_tax_import, Run]
 Index: [],
 'c_tax_res': Empty DataFrame
 Columns: [c_tax_res, Run]
 Index: [],
 'co2_limit':    co2_limit  Run
 0        inf    0,
 'co2_limit_max':    co2_limit_max  Run
 0       -1000000    0,
 'cooling_month':     cooling_month  Run
 1           0.000    0
 2           0.000    0
 3           0.000    0
 4           0.000    0
 5           0.058    0
 6           0.203    0
 7           0.484    0
 8           0.246    0
 9           0.009    0
 10          0.000    0
 11          0.000    0
 12          0.000    0,
 'e_density': Empty DataFrame
 Columns: [e_density, Run]
 Index: [],
 'elec_export_month':     elec_export_month  Run
 1             0.08605    0
 2             0.08208    0
 3             0.09112    0
 4             0.07488    0
 5             0.07087    0
 6             0.08580    0
 7             0.09699    0
 8             0.09937    0
 9             0.08178    0
 10            0.06715    0
 11            0.07797    0
 12            0.08594    0,
 'end_uses_demand_year':                             end_uses_demand_year  Run
 index0      index1
 ACETIC_ACID AGRICULTURE                      0.0    0
             EXPORT                           0.0    0
             HOUSEHOLDS                       0.0    0
             INDUSTRY                         0.0    0
             SERVICES                         0.0    0
 ...                                          ...  ...
 STEEL       EXPORT                           0.0    0
             HOUSEHOLDS                       0.0    0
             INDUSTRY                         0.0    0
             SERVICES                         0.0    0
             TRANSPORTATION                   0.0    0

 [210 rows x 2 columns],
 'end_uses_input':                         end_uses_input  Run
 index
 ACETIC_ACID                   0.000000    0
 ACETONE                       0.000000    0
 ALUMINUM                      0.000000    0
 BIO_JETFUEL                   0.000000    0
 BIO_METHANOL                  0.000000    0
 CEMENT                        0.000000    0
 ELECTRICITY_EHV            8153.216673    0
 ELECTRICITY_EHV_EXPORT    35556.000000    0
 ELECTRICITY_HV            83946.406402    0
 ELECTRICITY_LV            33995.663975    0
 ELECTRICITY_MV            20141.195602    0
 FOOD                          0.000000    0
 HEAT_HIGH_T               87056.154908    0
 HEAT_LOW_T_HW             19956.031506    0
 HEAT_LOW_T_SC              7357.205441    0
 HEAT_LOW_T_SH             95224.623347    0
 JETFUEL                       0.000000    0
 LIGHTING                  29065.043617    0
 METHANOL                      0.000000    0
 MOBILITY_FREIGHT_ELD     114381.818271    0
 MOBILITY_FREIGHT_LD       22626.525339    0
 MOBILITY_FREIGHT_MD       29451.914883    0
 MOBILITY_FREIGHT_SD       12536.444649    0
 MOBILITY_PASSENGER_ELD        0.000000    0
 MOBILITY_PASSENGER_LD     61446.766651    0
 MOBILITY_PASSENGER_MD     54825.051096    0
 MOBILITY_PASSENGER_SD     62939.044515    0
 PAPER                         0.000000    0
 PE                            0.000000    0
 PET                           0.000000    0
 PHENOL                        0.000000    0
 PP                            0.000000    0
 PS                            0.000000    0
 PVC                           0.000000    0
 STEEL                         0.000000    0,
 'f_grid_ext':              f_grid_ext  Run
 EHP_H2_GRID    0.000000    0
 EHP_NG_GRID    9.670442    0
 EHV_GRID      35.948127    0
 HP_H2_GRID     0.000000    0
 HP_NG_GRID     9.670442    0
 HV_GRID       30.680583    0
 LP_H2_GRID     0.000000    0
 LP_NG_GRID     4.986711    0
 LV_GRID       21.794526    0
 MP_H2_GRID     0.000000    0
 MP_NG_GRID     9.653959    0
 MV_GRID       23.895296    0,
 'f_max':                          f_max  Run
 index
 AFC                    10000.0    0
 ALKALINE_ELECTROLYSIS  10000.0    0
 AL_MAKING              10000.0    0
 AL_MAKING_HR           10000.0    0
 AN_DIG                 10000.0    0
 ...                        ...  ...
 TRUCK_SH_PROPANE_SD    10000.0    0
 UNMINEABLE_COAL_SEAM       0.0    0
 WIND_OFFSHORE           2179.0    0
 WIND_ONSHORE               0.0    0
 WOOD_METHANOL          10000.0    0

 [690 rows x 2 columns],
 'f_min':                        f_min  Run
 index
 AFC                      0.0    0
 ALKALINE_ELECTROLYSIS    0.0    0
 AL_MAKING                0.0    0
 AL_MAKING_HR             0.0    0
 AN_DIG                   0.0    0
 ...                      ...  ...
 TRUCK_SH_PROPANE_SD      0.0    0
 UNMINEABLE_COAL_SEAM     0.0    0
 WIND_OFFSHORE            0.0    0
 WIND_ONSHORE             0.0    0
 WOOD_METHANOL            0.0    0

 [690 rows x 2 columns],
 'fmax_perc':                            fmax_perc  Run
 index
 AFC                                1    0
 AL_MAKING                          1    0
 AL_MAKING_HR                       1    0
 AN_DIG_SI                          1    0
 BIOMETHANE_TO_BIOMETHANOL          1    0
 ...                              ...  ...
 TRUCK_SH_PROPANE_MD                1    0
 TRUCK_SH_PROPANE_SD                1    0
 WIND_OFFSHORE                      1    0
 WIND_ONSHORE                       1    0
 WOOD_METHANOL                      1    0

 [421 rows x 2 columns],
 'fmax_perc_mob':                           fmax_perc_mob  Run
 index
 BULK_CARRIER_BIOMEOH_ELD              1    0
 BULK_CARRIER_BIO_ELD                  1    0
 BULK_CARRIER_ELD                      1    0
 BULK_CARRIER_MEOH_ELD                 1    0
 BUS_BIODIESEL_B100_SD                 1    0
 ...                                 ...  ...
 TRUCK_SH_GASOLINE_SD                  1    0
 TRUCK_SH_HY_DIESEL_MD                 1    0
 TRUCK_SH_HY_DIESEL_SD                 1    0
 TRUCK_SH_PROPANE_MD                   1    0
 TRUCK_SH_PROPANE_SD                   1    0

 [307 rows x 2 columns],
 'fmin_perc':                            fmin_perc  Run
 index
 AFC                                0    0
 AL_MAKING                          0    0
 AL_MAKING_HR                       0    0
 AN_DIG_SI                          0    0
 BIOMETHANE_TO_BIOMETHANOL          0    0
 ...                              ...  ...
 TRUCK_SH_PROPANE_MD                0    0
 TRUCK_SH_PROPANE_SD                0    0
 WIND_OFFSHORE                      0    0
 WIND_ONSHORE                       0    0
 WOOD_METHANOL                      0    0

 [421 rows x 2 columns],
 'fmin_perc_mob':                           fmin_perc_mob  Run
 index
 BULK_CARRIER_BIOMEOH_ELD              0    0
 BULK_CARRIER_BIO_ELD                  0    0
 BULK_CARRIER_ELD                      0    0
 BULK_CARRIER_MEOH_ELD                 0    0
 BUS_BIODIESEL_B100_SD                 0    0
 ...                                 ...  ...
 TRUCK_SH_GASOLINE_SD                  0    0
 TRUCK_SH_HY_DIESEL_MD                 0    0
 TRUCK_SH_HY_DIESEL_SD                 0    0
 TRUCK_SH_PROPANE_MD                   0    0
 TRUCK_SH_PROPANE_SD                   0    0

 [307 rows x 2 columns],
 'gwp_constr':                        gwp_constr  Run
 index
 AFC                             0    0
 ALKALINE_ELECTROLYSIS           0    0
 AL_MAKING                       0    0
 AL_MAKING_HR                    0    0
 AN_DIG                          0    0
 ...                           ...  ...
 TRUCK_SH_PROPANE_SD             0    0
 UNMINEABLE_COAL_SEAM            0    0
 WIND_OFFSHORE                   0    0
 WIND_ONSHORE                    0    0
 WOOD_METHANOL                   0    0

 [690 rows x 2 columns],
 'gwp_e':                     gwp_e  Run
 index0      index1
 ACETIC_ACID 1           0    0
             2           0    0
             3           0    0
             4           0    0
             5           0    0
 ...                   ...  ...
 XYLENE      8           0    0
             9           0    0
             10          0    0
             11          0    0
             12          0    0

 [1008 rows x 2 columns],
 'heating_month':     heating_month  Run
 1          0.1984    0
 2          0.1654    0
 3          0.1421    0
 4          0.0319    0
 5          0.0000    0
 6          0.0000    0
 7          0.0000    0
 8          0.0000    0
 9          0.0147    0
 10         0.0898    0
 11         0.1383    0
 12         0.2194    0,
 'i_rate':    i_rate  Run
 0    0.04    0,
 'k_security':              k_security  Run
 EHP_H2_GRID           6    0
 EHP_NG_GRID           6    0
 EHV_GRID              6    0
 HP_H2_GRID            6    0
 HP_NG_GRID            6    0
 HV_GRID               6    0
 LP_H2_GRID            6    0
 LP_NG_GRID            6    0
 LV_GRID               6    0
 MP_H2_GRID            6    0
 MP_NG_GRID            6    0
 MV_GRID               6    0,
 'l_grid_ext':              l_grid_ext  Run
 EHP_H2_GRID         789    0
 EHP_NG_GRID         789    0
 EHV_GRID          12581    0
 HP_H2_GRID           76    0
 HP_NG_GRID           76    0
 HV_GRID           22341    0
 LP_H2_GRID         7560    0
 LP_NG_GRID         7560    0
 LV_GRID          108096    0
 MP_H2_GRID         1966    0
 MP_NG_GRID         1966    0
 MV_GRID          120472    0,
 'l_grid_ref':              l_grid_ref  Run
 EHP_H2_GRID   39.450000    0
 EHP_NG_GRID   39.450000    0
 EHV_GRID     285.931818    0
 HP_H2_GRID     0.655172    0
 HP_NG_GRID     0.655172    0
 HV_GRID       27.996241    0
 LP_H2_GRID     0.017182    0
 LP_NG_GRID     0.017182    0
 LV_GRID        0.023757    0
 MP_H2_GRID     0.964198    0
 MP_NG_GRID     0.964198    0
 MV_GRID       37.647500    0,
 'layers_in_out':                                            layers_in_out  Run
 index0      index1
 ACETIC_ACID ACETIC_ACID                              1.0    0
             ACETONE                                  0.0    0
             ALUMINUM                                 0.0    0
             BENZENE                                  0.0    0
             BIOMASS_AGRICULTURE_DEJECTION            0.0    0
 ...                                                  ...  ...
 XYLENE      WASTE_BIO                                0.0    0
             WASTE_FOS                                0.0    0
             WET_BIOMASS                              0.0    0
             WOOD                                     0.0    0
             XYLENE                                   1.0    0

 [74035 rows x 2 columns],
 'lifetime':                        lifetime  Run
 index
 AFC                        35.0    0
 ALKALINE_ELECTROLYSIS      10.0    0
 AL_MAKING                  25.0    0
 AL_MAKING_HR               25.0    0
 AN_DIG                     25.0    0
 ...                         ...  ...
 TRUCK_SH_PROPANE_SD        15.0    0
 UNMINEABLE_COAL_SEAM       25.0    0
 WIND_OFFSHORE              25.0    0
 WIND_ONSHORE               25.0    0
 WOOD_METHANOL              20.0    0

 [690 rows x 2 columns],
 'lighting_month':     lighting_month  Run
 1           0.1240    0
 2           0.1020    0
 3           0.0918    0
 4           0.0708    0
 5           0.0588    0
 6           0.0438    0
 7           0.0408    0
 8           0.0398    0
 9           0.0678    0
 10          0.1048    0
 11          0.1238    0
 12          0.1318    0,
 'loss_coeff':                   loss_coeff  Run
 index
 ACETIC_ACID         0.000000    0
 ACETONE             0.000000    0
 ALUMINUM            0.000000    0
 BIO_METHANOL        0.000000    0
 CEMENT              0.000000    0
 ELECTRICITY_EHV     0.030900    0
 ELECTRICITY_HV      0.000145    0
 ELECTRICITY_LV      0.000491    0
 ELECTRICITY_MV      0.001460    0
 FOOD                0.000000    0
 HEAT_HIGH_T         0.000000    0
 HEAT_LOW_T_DECEN    0.000000    0
 HEAT_LOW_T_DHN      0.050000    0
 METHANOL            0.000000    0
 MOB_FREIGHT_ELD     0.000000    0
 MOB_FREIGHT_LD      0.000000    0
 MOB_FREIGHT_MD      0.000000    0
 MOB_FREIGHT_SD      0.000000    0
 MOB_PRIVATE_ELD     0.000000    0
 MOB_PRIVATE_LD      0.000000    0
 MOB_PRIVATE_MD      0.000000    0
 MOB_PRIVATE_SD      0.000000    0
 MOB_PUBLIC_ELD      0.000000    0
 MOB_PUBLIC_LD       0.000000    0
 MOB_PUBLIC_MD       0.000000    0
 MOB_PUBLIC_SD       0.000000    0
 PAPER               0.000000    0
 PE                  0.000000    0
 PET                 0.000000    0
 PHENOL              0.000000    0
 PP                  0.000000    0
 PS                  0.000000    0
 PVC                 0.000000    0
 STEEL               0.000000    0,
 'n_stations':              n_stations  Run
 EHP_H2_GRID          20    0
 EHP_NG_GRID          20    0
 EHV_GRID             44    0
 HP_H2_GRID          116    0
 HP_NG_GRID          116    0
 HV_GRID             798    0
 LP_H2_GRID       440000    0
 LP_NG_GRID       440000    0
 LV_GRID         4550000    0
 MP_H2_GRID         2039    0
 MP_NG_GRID         2039    0
 MV_GRID            3200    0,
 'out_max':                        out_max  Run
 index
 AFC                        inf    0
 ALKALINE_ELECTROLYSIS      inf    0
 AL_MAKING                  inf    0
 AL_MAKING_HR               inf    0
 AN_DIG                     inf    0
 ...                        ...  ...
 TRUCK_SH_PROPANE_SD        inf    0
 UNMINEABLE_COAL_SEAM       inf    0
 WIND_OFFSHORE              inf    0
 WIND_ONSHORE               inf    0
 WOOD_METHANOL              inf    0

 [687 rows x 2 columns],
 'out_min':                        out_min  Run
 index
 AFC                          0    0
 ALKALINE_ELECTROLYSIS        0    0
 AL_MAKING                    0    0
 AL_MAKING_HR                 0    0
 AN_DIG                       0    0
 ...                        ...  ...
 TRUCK_SH_PROPANE_SD          0    0
 UNMINEABLE_COAL_SEAM         0    0
 WIND_OFFSHORE                0    0
 WIND_ONSHORE                 0    0
 WOOD_METHANOL                0    0

 [687 rows x 2 columns],
 'peak_dhn_factor':    peak_dhn_factor  Run
 0                1    0,
 'ref_size':                            ref_size  Run
 index
 ALKALINE_ELECTROLYSIS         0.001    0
 AL_MAKING                    10.000    0
 AL_MAKING_HR                 10.000    0
 AN_DIG_SI                     0.005    0
 BIOETHANOL_TO_BIOJETFUELS     0.115    0
 ...                             ...  ...
 TRAIN_SNG                     0.053    0
 TRAMWAY                       0.004    0
 UNMINEABLE_COAL_SEAM          0.001    0
 WIND_ONSHORE                  0.003    0
 WOOD_METHANOL                 0.001    0

 [235 rows x 2 columns],
 'renew':    renew  Run
 0      0    0,
 'reno_max':    reno_max  Run
 0         0    0,
 'reno_min':    reno_min  Run
 0         0    0,
 'reno_share_max':    reno_share_max  Run
 0             0.5    0,
 'reno_share_min':    reno_share_min  Run
 0               0    0,
 'share_freight_air_max_eld':    share_freight_air_max_eld  Run
 0                     0.0063    0,
 'share_freight_air_min_eld':    share_freight_air_min_eld  Run
 0                     0.0063    0,
 'share_freight_maritime_bulk_carrier':    share_freight_maritime_bulk_carrier  Run
 0                                 0.56    0,
 'share_freight_maritime_container':    share_freight_maritime_container  Run
 0                              0.17    0,
 'share_freight_maritime_max_eld':    share_freight_maritime_max_eld  Run
 0                          0.5879    0,
 'share_freight_maritime_min_eld':    share_freight_maritime_min_eld  Run
 0                          0.5879    0,
 'share_freight_maritime_oil_tanker':    share_freight_maritime_oil_tanker  Run
 0                               0.26    0,
 'share_freight_rail_max_eld':    share_freight_rail_max_eld  Run
 0                      0.2209    0,
 'share_freight_rail_max_ld':    share_freight_rail_max_ld  Run
 0                     0.3723    0,
 'share_freight_rail_min_eld':    share_freight_rail_min_eld  Run
 0                      0.2209    0,
 'share_freight_rail_min_ld':    share_freight_rail_min_ld  Run
 0                     0.3723    0,
 'share_heat_dhn_max':    share_heat_dhn_max  Run
 0                 0.5    0,
 'share_heat_dhn_min':    share_heat_dhn_min  Run
 0                   0    0,
 'share_mobility_public_max_eld':    share_mobility_public_max_eld  Run
 0                              1    0,
 'share_mobility_public_max_ld':    share_mobility_public_max_ld  Run
 0                        0.8865    0,
 'share_mobility_public_max_md':    share_mobility_public_max_md  Run
 0                        0.0039    0,
 'share_mobility_public_max_sd':    share_mobility_public_max_sd  Run
 0                        0.1146    0,
 'share_mobility_public_min_eld':    share_mobility_public_min_eld  Run
 0                              0    0,

In [ ]:
result_2050.variables['F_Mult']

                         F_Mult  Run
index
AFC                    0.002723    0
ALKALINE_ELECTROLYSIS  0.000000    0
AL_MAKING              0.000000    0
AL_MAKING_HR           0.000000    0
AN_DIG                 0.000000    0
...                         ...  ...
TRUCK_SH_PROPANE_SD    0.000000    0
UNMINEABLE_COAL_SEAM   0.000000    0
WIND_OFFSHORE          0.000000    0
WIND_ONSHORE           0.000000    0
WOOD_METHANOL          0.000000    0

[690 rows x 2 columns]

In [27]:
result_2050.variables['F_Mult'].loc[['AFC', 'WIND_ONSHORE', 'HYDRO_RIVER']]

                 F_Mult  Run
index
AFC            0.002723    0
WIND_ONSHORE   0.000000    0
HYDRO_RIVER   15.130000    0

In [30]:
result_2050.variables['Annual_Prod'].loc[['AFC', 'WIND_ONSHORE', 'HYDRO_RIVER']]

               Annual_Prod  Run
index
AFC               5.946774    0
WIND_ONSHORE      0.000000    0
HYDRO_RIVER   73573.195680    0

In [34]:
result_2050.variables['Annual_Res'].loc[['RES_HYDRO', 'RES_SOLAR']]

              Annual_Res  Run
index
RES_HYDRO  205294.656402    0
RES_SOLAR      22.573488    0